dist: bionic
language: cpp

matrix:
  - os: linux
    env:
      - TASK="bionic gcc"
    compiler: gcc
    script:
      - make test -j

  - os: linux
    env:
      - TASK="bionic clang"
    compiler: clang
    script:
      - make test -j

  - os: linux
    env:
      - TASK="asan"
    compiler: gcc
    script:
      - make asan -j

  - os: linux
    env:
      - TASK="tsan"
    compiler: gcc
    script:
      - make tsan -j

  - os: linux
    env:
      - TASK="ubsan"
    compiler: gcc
    script:
      - make ubsan -j

  - os: linux
    env:
      - TASK="cov"
    compiler: gcc
    script:
      - make cov -j
    after_success:
      - bash <(curl -s https://codecov.io/bash)
