os: linux
language: cpp

branches:
  only:
    - master

matrix:
  - name: "bionic gcc"
    dist: bionic
    compiler: gcc
    script:
      - make test -j

  - name: "bionic clang"
    dist: bionic
    compiler: clang
    script:
      - make test -j

  - name: "focal gcc"
    dist: focal
    compiler: gcc
    script:
      - make test -j

  - name: "focal clang"
    dist: focal
    compiler: clang
    script:
      - make test -j

  - name: "asan"
    dist: focal
    compiler: gcc
    script:
      - make asan -j

  - name: "tsan"
    dist: focal
    compiler: gcc
    script:
      - make tsan -j

  - name: "ubsan"
    dist: focal
    compiler: gcc
    script:
      - make ubsan -j

  - name: "valgrind"
    dist: focal
    addons:
      apt:
        packages:
          - valgrind
    compiler: gcc
    script:
      - make valgrind -j

  - name: "iwyu"
    dist: focal
    addons:
      apt:
        packages:
          - clang-9.0
          - iwyu
    compiler: clang
    script:
      - make iwyu -j

  - name: "clang-tidy"
    dist: focal
    addons:
      apt:
        packages:
          - clang-tidy
    compiler: clang
    script:
      - clang-tidy include/**/*.h src/*.c src/*.h -- -Iinclude
      - clang-tidy src/*.cpp src/*.hpp -- -Iinclude -I. -std=c++17

  - name: "cov"
    dist: focal
    compiler: gcc
    script:
      - make cov -j
    after_success:
      - bash <(curl -s https://codecov.io/bash)
