os: linux
dist: bionic
language: cpp

matrix:
  - name: "bionic gcc"
    compiler: gcc
    script:
      - make test -j

  - name: "bionic clang"
    compiler: clang
    script:
      - make test -j

  - name: "asan"
    compiler: gcc
    script:
      - make asan -j

  - name: "tsan"
    compiler: gcc
    script:
      - make tsan -j

  - name: "ubsan"
    compiler: gcc
    script:
      - make ubsan -j

  - name: "cov"
    compiler: gcc
    script:
      - make cov -j
    after_success:
      - bash <(curl -s https://codecov.io/bash)
