os: linux
dist: bionic
language: cpp

branches:
  only:
    - master

matrix:
  - name: "bionic gcc"
    compiler: gcc
    script:
      - make test -j

  - name: "bionic clang"
    compiler: clang
    script:
      - make test -j

  - name: "asan"
    compiler: gcc
    script:
      - make asan -j

  - name: "tsan"
    compiler: gcc
    script:
      - make tsan -j

  - name: "ubsan"
    compiler: gcc
    script:
      - make ubsan -j

  - name: "valgrind"
    addons:
      apt:
        packages:
          - valgrind
    compiler: gcc
    script:
      - make valgrind -j

  - name: "iwyu"
    addons:
      apt:
        packages:
          - clang-5.0
          - iwyu
    compiler: clang
    script:
      - make iwyu -j

  - name: "cov"
    compiler: gcc
    script:
      - make cov -j
    after_success:
      - bash <(curl -s https://codecov.io/bash)
