name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  bionic_gcc:
    name: Ubuntu Bionic Default GCC

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:18.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: make test -j

  focal_gcc:
    name: Ubuntu Focal Default GCC

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: make test -j

  bionic_clang:
    name: Ubuntu Bionic Default Clang

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:18.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y clang make
    - name: run
      run: CC=clang CXX=clang++ make test -j

  focal_clang:
    name: Ubuntu Focal Default Clang

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y clang make
    - name: run
      run: CC=clang CXX=clang++ make test -j

  asan:
    name: Address Sanitizer

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: make asan -j

  tsan:
    name: Thread Sanitizer

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: make tsan -j

  ubsan:
    name: Undefined Behavior Sanitizer

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: make ubsan -j

  valgrind:
    name: Valgrind

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make valgrind
    - name: run
      run: make valgrind -j

  iwyu:
    name: Include What You Use

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y clang-9 iwyu make
    - name: run
      run: make iwyu -j

  clang_tidy:
    name: Clang-Tidy

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y clang-tidy
    - name: run
      run: |
        clang-tidy include/**/*.h src/*.c src/*.h -- -Iinclude
        clang-tidy src/*.cpp src/*.hpp -- -Iinclude -I. -std=c++17

  cov:
    name: Code Coverage

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y g++ make
    - name: run
      run: |
        make cov -j
    - uses: codecov/codecov-action@v1
